### ISSUE TITLE
Add support for removing unwanted items from menu system.

### ISSUE THREAD

**Issue by N6REJ** [neard/neard#266]
While the menu system imo is the best out there having to keep so many unused modules in the menu is annoying.
I don't use mongo nor drupal nor wordpress nor notepad2 and really don't want them in my menu system.
as for notepad2 I'd MUCH prefer notepad++ be there as its fantastic!
imo if the item is turned off in the config, then it should not show up in the menu.  OR, have another flag which says leave it out of the menu.
A good example is WP.. While I can't stand it, there may come a time with the company I help out with where I'm forced to work on WP code.  In that case the WP function would be nice to turn on TEMPORARILY!
So, that module I might not turn off completely just leave it in the off state in the menu.

**Comment by crazy-max** [comment]
Oh you talk about WP-CLI ?
Yes we could remove all unwanted items from the menu but i have to rewrite the whole system tray app because [aetraymenu](https://obroekma.home.xs4all.nl/aetraymenu/) does'nt provide this kind of stuff.
This will be in a major release.

And again thanks for your feedback ;)

**Comment by StaggerLeee** [comment]
Some groove estimate when new menu could be finished ?
