### ISSUE TITLE
Disable tools

### ISSUE THREAD

**Issue by gamevnlc** [neard/neard#362]
Hello, I would like to know how to disable tools in neard. Is it possible to do it? Thank you

**Comment by N6REJ** [comment]
all of tools or certain ones?

**Comment by crazy-max** [comment]
Hi @gamevnlc,

For the moment there are no methods to disable the tools because some of them depend on modules. I have to implement this behaviour. But if you want to disable them, you can simply delete the folder. For example, for Git delete the contents of the `tools\git\` folder (do not delete the git folder itself on the other hand)

**Comment by gamevnlc** [comment]
@N6REJ 
Only python. 
@crazy-max I got it . Thank you.

**Comment by Lpern** [comment]
two minor questions about this @crazy-max:

1.   are there any tools this does not work with? (before I go deleting things)
2.   Will this decrease the server start-time overhead?

Also, I would like to thank you for this wonderful server software stack. It's existence is making my life a lot easier for Drupal server development. I tip my hat to you sir, and will donate accordingly.

**Comment by crazy-max** [comment]
Hi @Lpern,

1. Required tool should be console (I think I will add some explanations in the FAQ about this and maybe I will embed Console in core on the next release)
2. On the contrary it will be faster because there will be fewer files to scan to check the paths if Neard's location has changed.

Thank you for your support I really appreciate it :)
