### ISSUE TITLE
Update MongoDB to 3.7.9

### ISSUE THREAD

**Issue by qodrinzo** [neard/neard#372]
Would you mind updating MongoDB into a newer version like the most recent one, 3.7.9? I've tried building a release out of neard/dev package, but Neard 1.4 throws a startup error:

> MongoDB 3.7.9 (neardmongodb) service cannot be installed : - Cannot start the service : Error 41d (1053 : )

Please make it happen! thx

**Comment by crazy-max** [comment]
It will be done when I have some time ;)
Thanks for your contrib

**Comment by N6REJ** [comment]
@crazy-max while your at it, seems you can't disabled the mongo extension from php via the menu

**Comment by crazy-max** [comment]
@qodrinzo After digging, MongoDB >= 3.6 [removes the deprecated HTTP interface and REST API](https://docs.mongodb.com/manual/release-notes/3.6-compatibility/#http-interface-and-rest-api).
Since Neard uses the REST interface to retrieve the server status, it is no longer possible to check the status.

However, you can still run the service but you must remove the following lines in `mongodb.conf` :

```
  http:
    enabled: true
    RESTInterfaceEnabled: true
```

I've been thinking about using mongo CLI (`--quiet 127.0.0.1:27017 --eval "JSON.stringify(db.runCommand( { serverStatus: 1 } ))"`) to retrieve this information but it requires many changes in the core and I don't foresee any evolution at the moment.

PRs are welcome :wink:

**Comment by crazy-max** [comment]
@qodrinzo MongoDB 3.4.24, 3.6.17, 4.0.17, 4.2.5 are available. MongoDB 3.6+ works on Neard 1.6.4+.
