### ISSUE TITLE
1.5 update instructions

### ISSUE THREAD

**Issue by N6REJ** [neard/neard#401]
@crazy-max any instructions on the 1.5 update?

**Comment by crazy-max** [comment]
Hi @N6REJ, no need for instructions, only modules have been updated for this release

**Comment by myspulin** [comment]
Hi, I have some questions and points for versioning. Is it needed to increase version to 1.5 if there is no binary change, I mean just modules update? What about 1.4.1? Because I have expected some major changes and that is why I also checked the changelog to get instructions for update. It would be nice to have change log saying "only these modules were updated". The application shows still version 1.4 even I update modules, so it is really confusing. I do not say this is something wrong I just want to open some discussions because obviously I am not the only one having some troubles. I love this app! Thank you.

**Comment by N6REJ** [comment]
you have to change the core folder also.  I had the same problem until then..  so, 

1)  replace neard.ini
2) replace neard.exe
3) replace core folder
I also replaced the .dat files in root neard but idk if thats necessary.

**Comment by crazy-max** [comment]
@myspulin @N6REJ I have added upgrade notes : https://neard.io/doc/upgrade-notes/

**Comment by b10tds** [comment]
Exactly what does "required : Remove then replace folder core" mean please.
